/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AD&D  4D (https://sketchfab.com/add4d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/la-luna-viaje-virtual-guiado-3d-vr-f2cdadece5b54fadaddd80e881e4b848
Title: La Luna / Viaje Virtual Guiado / 3D /  VR
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { animations } from 'motion/react';

export function Moon(props) {
  const { nodes, materials } = useGLTF('models/la_luna__viaje_virtual_guiado__3d___vr.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.224, -0.185, 0.172]} rotation={[-1.722, -0.224, 0.007]} scale={0.433}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['Material.001']}
          position={[-0.446, -1.652, -0.032]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/la_luna__viaje_virtual_guiado__3d___vr.glb')